apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-1
spec:
  selector:
    matchLabels:
      name: daemonset-cndk
  template:
    metadata:             
      labels:
        name: daemonset-cndk
    spec:
      containers:
      - name: daemonset-pod
        image: nginx