apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:               
      memory: 256Mi
      cpu: 250m
    defaultRequest:      
      memory: 128Mi
      cpu: 125m
    max:               
      memory: 0.5Gi
      cpu: 500m
    min:                
      memory: 100Mi
      cpu: 100m
    type: Container     