apiVersion: v1
kind: Pod
metadata:
  name: limit-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["tail"]
    args: ["-f", "/dev/null"]
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"