apiVersion: v1
kind: Pod
metadata:
 name: pod-preferred
spec:
 affinity:
  nodeAffinity:
   preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
       matchExpressions:
       - {key: cserver, operator: Exists}
 containers:
 - name: container
   image: nginx:1.20-alpine
 terminationGracePeriodSeconds: 0