apiVersion: v1
kind: Pod
metadata:
 name: pod-required
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:   
    nodeSelectorTerms:
    - matchExpressions:
      -  {key: cserver, operator: Exists}
 containers:
 - name: container
   image: nginx:1.20-alpine
 terminationGracePeriodSeconds: 0