apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ns1
  labels:
    app: webpod
spec:
  containers:
  - name: container
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: ns1
  labels:
    app: webpod
spec:
  containers:
  - name: container
    image: gcr.io/google-samples/kubernetes-bootcamp:v1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: ns1
spec:
  ports:
    - port: 9001
      targetPort: 80
  selector:
    app: webpod
  type: ClusterIP