apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ns2
  labels:
    app: webpod2
spec:
  containers:
  - name: container
    image: gcr.io/google-samples/kubernetes-bootcamp:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: ns2
  labels:
    app: webpod2
spec:
  containers:
  - name: container
    image: gcr.io/google-samples/kubernetes-bootcamp:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-web2
  namespace: ns2
spec:
  ports:
    - port: 9002
      targetPort: 8080
  selector:
    app: webpod2
  type: ClusterIP