apiVersion: v1
kind: Namespace
metadata:
  name: ns3
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-pod-count
  namespace: ns3
spec:
  hard:
    count/pods: 3
    count/services: 1