apiVersion: v1
kind: Pod
metadata:
  name: pod-exceed
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["tail"]
    args: ["-f", "/dev/null"]
    resources:
      limits:
        memory: "800Mi"
        cpu: "750m"
      requests:
        memory: "500Mi"
        cpu: "500m"