apiVersion: v1
kind: Pod
metadata:
 name: cache1
spec:
 affinity:
  podAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:   
   - topologyKey: team      # 노드의 키
     labelSelector:
      matchExpressions:
      -  {key: type, operator: In, values: [web1]}    # 파드의 키
 containers:
 - name: container
   image: redis:6.2-alpine
 terminationGracePeriodSeconds: 0