apiVersion: v1
kind: Pod
metadata:
 name: cache2
spec:
 affinity:
  podAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:   
   - topologyKey: team
     labelSelector:
      matchExpressions:
      -  {key: type, operator: In, values: [web2]}
 containers:
 - name: container
   image: redis:6.2-alpine
 terminationGracePeriodSeconds: 0