apiVersion: v1
kind: Pod
metadata:
 name: pod1-toleration
spec:
 nodeSelector:
  ssd: storage1
 tolerations:
 - effect: NoSchedule
   key: disk
   operator: Equal
   value: ssd
 containers:
 - name: container
   image: nginx:1.20-alpine
 terminationGracePeriodSeconds: 0