apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 5Gi      
  accessModes:
    - ReadWriteOnce    
  awsElasticBlockStore:
    fsType: ext4
    volumeID: <VOLUME_ID>