apiVersion: v1
kind: Service
metadata:
  name: aws-svc-clb
spec:
  ports:
    - name: awsclb-webport
      port: 80
      targetPort: 8080
      nodePort: 30000
  selector:
    app: deploy-websrv
  type: LoadBalancer
