apiVersion: v1
kind: Service
metadata:
  name: aws-svc-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
    - name: awsnlb-webport
      port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app: deploy-websrv
  type: LoadBalancer
