apiVersion: v1
kind: Service
metadata:
  name: svc-mtlb-1
spec:
  ports:
    - name: svc-mtlb-webport
      port: 9000
      targetPort: 8080
      nodePort: 30001
  selector:
    app: deploy-websrv
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mtlb-2
spec:
  ports:
    - name: svc-mtlb-webport
      port: 9000
      targetPort: 8080
      nodePort: 30002
  selector:
    app: deploy-websrv
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mtlb-3
spec:
  ports:
    - name: svc-mtlb-webport
      port: 9000
      targetPort: 8080
      nodePort: 30003
  selector:
    app: deploy-websrv
  type: LoadBalancer
