apiVersion: v1
kind: Service
metadata:
  name: k3s-svc-lb
spec:
  ports:
    - name: k3slb-webport
      port: 8000
      targetPort: 8080
      nodePort: 31000
  selector:
    app: deploy-websrv
  type: LoadBalancer
